# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: "2025 smdn <smdn@smdn.jp>"
#
# ref: https://docs.github.com/code-security/dependabot/working-with-dependabot/dependabot-options-reference
#
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github-actions-workflows:
        patterns:
          - "actions/*"
      smdn-fundamentals-workflows:
        patterns:
          - "smdn/Smdn.Fundamentals/*"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "03:13"
      timezone: "Asia/Tokyo"
# not works as expected
#   ref: https://github.com/dependabot/dependabot-core/issues/12270
#   ref: https://github.com/dependabot/dependabot-core/issues/11479
#
#  - package-ecosystem: "nuget"
#    directory: "/"
#    groups:
#      smdn-msbuild-projectassets:
#        patterns:
#          - "Smdn.MSBuild.ProjectAssets.Common"
#          - "Smdn.MSBuild.ProjectAssets.Library"
#    schedule:
#      interval: "weekly"
#      day: "wednesday"
#      time: "03:16"
#      timezone: "Asia/Tokyo"
