# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: "2025 smdn <smdn@smdn.jp>"

name: Run NuGet Login reusable workflow

permissions:
  id-token: write # required for GitHub OIDC / NuGet.org Trusted Publishing

on:
  workflow_dispatch:

jobs:
  run-publish-release-target:
    uses: smdn/Smdn.Fundamentals/.github/workflows/nuget-login.yml@devel-workflows
    secrets:
      username_nuget_org: ${{ secrets.USERNAME_NUGET_ORG }}
